### ISSUE TITLE
Why do you check if query filters on ID and then stop the query?

### ISSUE THREAD

**Issue by kevinvanmierlo** [lekoala/silverstripe-softdelete#6]
We had a problem that we were querying by ID and it would find the deleted items.  It would make sense to me that default it shouldn't find anything that is soft deleted. And if you do, you can use `SoftDeletable.filter` to make sure you can find it. It breaks our code now and we have to do extra checks to make sure it doesn't get a deleted object.

**Comment by lekoala** [comment]
@kevinvanmierlo yes i understand how that can be confusing. Here is my take on it: if you request a deleted item for some reason (for example, you visit /show/some_deleted_id) and do a get()->byID(), you should anyway implement a proper canView check

If you want to display a deleted item (in the admin for example), filtering them becomes quickly difficult to deal with due to how it works in the cms. Querying by id can also lead to records being cached/not cached, it can be tricky.

with that being said: i'm happy to add a yml config setting for that use case if you think it works better for you to filter also item when you request them specifically, i can add that ;-)
and it probably deserves some warning in the docs

**Comment by kevinvanmierlo** [comment]
@lekoala Ah yes, in the CMS is could get tricky. Our code which does the querying is mostly the API. So there it makes sense to also apply your filter when querying by ID. 

But I think it would be great to have the option! We'll have to take a look how to fix the CMS afterwards.

**Comment by lekoala** [comment]
@kevinvanmierlo it's on master with the updated readme. you can give it a try and let me know if that works for you

**Comment by kevinvanmierlo** [comment]
@lekoala That's really quick! 
I couldn't get the yaml working. But that will break the CMS stuff anyways. So we now use `SoftDeletable::config()->set('check_filters_on_id', false);` specifically on the API, so we don't have to do extra checks anymore. I think for us that's the perfect solution, thanks!

**Comment by lekoala** [comment]
@kevinvanmierlo maybe a missing dev/build or something like that? weird it works by direct assignation and not through yml
i'll keep it as is if it works for you

**Comment by kevinvanmierlo** [comment]
@lekoala No, I tried it twice because I though maybe that was what went wrong. It's definitely weird, but for our use case it doesn't really matter. Thank you!
